FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --only=production && npm cache clean --force

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD ["node", "src/server.js"]
